apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teastore
      run: teastore-auth
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-auth
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: teastore-auth
          image: descartesresearch/teastore-auth:1.4.2
          ports:
            - containerPort: 8080
          env:
            - name: HOST_NAME
              value: "teastore-auth"
            - name: REGISTRY_HOST
              value: "teastore-registry"
          readinessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: "/tools.descartes.teastore.auth/rest/ready/isready"
              port: 8080
              scheme: HTTP
          resources:
            limits:
              memory: 1000Mi
              cpu: 500m
