apiVersion: v1
kind: Service
metadata:
  name: teastore-webui
  labels:
    app: teastore
    run: teastore-webui
spec:
  type: NodePort
  ports:
    - port: 8080
      #nodePort: 30080
      protocol: TCP
  selector:
    run: teastore-webui
