apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-persistence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teastore
      run: teastore-persistence
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-persistence
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: teastore-persistence
          image: descartesresearch/teastore-persistence:development
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: HOST_NAME
              value: "teastore-persistence"
            - name: REGISTRY_HOST
              value: "teastore-registry"
            - name: DB_HOST
              value: "teastore-db"
            - name: DB_PORT
              value: "3306"
          readinessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: "/tools.descartes.teastore.persistence/rest/generatedb/finished"
              port: 8080
              scheme: HTTP
          resources:
            limits:
              memory: 4000Mi
              cpu: 2000m
