apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teastore
      run: teastore-image
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-image
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: teastore-image
          image: descartesresearch/teastore-image:1.4.2
          ports:
            - containerPort: 8080
          env:
            - name: HOST_NAME
              value: "teastore-image"
            - name: REGISTRY_HOST
              value: "teastore-registry"
          readinessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: "/tools.descartes.teastore.image/rest/image/finished"
              port: 8080
              scheme: HTTP
          # startupProbe:
          #   initialDelaySeconds: 15
          #   timeoutSeconds: 5
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 30
          #   httpGet:
          #     path: "/tools.descartes.teastore.image/rest/image/finished"
          #     port: 8080
          #     scheme: HTTP
          resources:
            limits:
              memory: 1000Mi
              cpu: 500m
